version: 0.0
os: linux
files:
    - source: /
      destination: /home/ubuntu/tennisapi
hooks:
    ApplicationStop:
        - location: deploy/stop_server.sh
          timeout: 300
          runas: ubuntu

    BeforeInstall:
        - location: deploy/before_install.sh
          timeout: 300
          runas: ubuntu

    AfterInstall:
        - location: deploy/after_install.sh
          timeout: 300
          runas: ubuntu

    ApplicationStart:
        - location: deploy/start_server.sh
          timeout: 300
          runas: ubuntu

    ValidateService:
        - location: deploy/validate_service.sh
          timeout: 300
          runas: ubuntu
